<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $categories = DB::table('categories')->pluck('id', 'slug')->toArray();
        
        $products = [
            // ==================== HANDPHONE (15 produk) ====================
            [
                'name' => 'iPhone 16 Pro Max',
                'category_slug' => 'handphone',
                'brand' => 'Apple',
                'price' => 18000000,
                'original_price' => 25000000,
                'stock' => 50,
                'sold' => 1234,
                'rating' => 4.8,
                'description' => 'iPhone 16 Pro Max dengan chip A18 Pro, kamera 48MP, dan baterai tahan seharian. Layar Super Retina XDR 6.9 inch. Dilengkapi dengan fitur AI canggih dan iOS 18 terbaru.',
                'is_flash_sale' => true,
                'discount' => 28,
                'flash_sale_end' => now()->addDays(1),
                'images' => [
                    'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&h=600&fit=crop',
                    'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&h=600&fit=crop&sat=-100',
                    'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&h=600&fit=crop&bright=0.9',
                    'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&h=600&fit=crop&con=0.8',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Hitam Titanium', 'stock' => 15],
                    ['type' => 'color', 'value' => 'Putih Titanium', 'stock' => 15],
                    ['type' => 'color', 'value' => 'Gold Titanium', 'stock' => 10],
                    ['type' => 'color', 'value' => 'Ungu Titanium', 'stock' => 10],
                    ['type' => 'size', 'value' => '128GB', 'stock' => 10],
                    ['type' => 'size', 'value' => '256GB', 'stock' => 20],
                    ['type' => 'size', 'value' => '512GB', 'stock' => 15],
                    ['type' => 'size', 'value' => '1TB', 'stock' => 5],
                ],
            ],
            [
                'name' => 'Samsung Galaxy S24 Ultra',
                'category_slug' => 'handphone',
                'brand' => 'Samsung',
                'price' => 19000000,
                'original_price' => 24000000,
                'stock' => 45,
                'sold' => 2345,
                'rating' => 4.7,
                'description' => 'Samsung Galaxy S24 Ultra dengan AI intelligence, kamera 200MP dengan zoom optik 10x, dan S-Pen terintegrasi. Layar Dynamic AMOLED 2X 6.8 inch 120Hz.',
                'is_flash_sale' => true,
                'discount' => 21,
                'flash_sale_end' => now()->addHours(12),
                'images' => [
                    'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&h=600&fit=crop',
                    'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&h=600&fit=crop&sat=-50',
                    'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&h=600&fit=crop&bright=1.1',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Titanium Black', 'stock' => 15],
                    ['type' => 'color', 'value' => 'Titanium Violet', 'stock' => 10],
                    ['type' => 'color', 'value' => 'Titanium Yellow', 'stock' => 10],
                    ['type' => 'color', 'value' => 'Titanium Green', 'stock' => 10],
                    ['type' => 'size', 'value' => '256GB', 'stock' => 20],
                    ['type' => 'size', 'value' => '512GB', 'stock' => 15],
                    ['type' => 'size', 'value' => '1TB', 'stock' => 10],
                ],
            ],
            [
                'name' => 'Xiaomi 14 Pro',
                'category_slug' => 'handphone',
                'brand' => 'Xiaomi',
                'price' => 12000000,
                'original_price' => 16000000,
                'stock' => 60,
                'sold' => 3456,
                'rating' => 4.6,
                'description' => 'Xiaomi 14 Pro dengan kamera Leica Summilux, Snapdragon 8 Gen 3, dan battery 4880mAh dengan fast charging 120W. Layar AMOLED 6.73 inch 120Hz.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&h=600&fit=crop',
                    'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&h=600&fit=crop&sat=-30',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 25],
                    ['type' => 'color', 'value' => 'Silver', 'stock' => 20],
                    ['type' => 'color', 'value' => 'Green', 'stock' => 15],
                    ['type' => 'size', 'value' => '256GB', 'stock' => 35],
                    ['type' => 'size', 'value' => '512GB', 'stock' => 25],
                ],
            ],
            [
                'name' => 'Google Pixel 8 Pro',
                'category_slug' => 'handphone',
                'brand' => 'Google',
                'price' => 16000000,
                'original_price' => 22000000,
                'stock' => 30,
                'sold' => 4567,
                'rating' => 4.7,
                'description' => 'Google Pixel 8 Pro dengan kamera AI terbaik, Tensor G3, dan 7 tahun update software. Layar LTPO OLED 6.7 inch 120Hz.',
                'is_flash_sale' => true,
                'discount' => 27,
                'flash_sale_end' => now()->addHours(8),
                'images' => [
                    'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&h=600&fit=crop',
                    'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&h=600&fit=crop&sat=-40',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Obsidian', 'stock' => 12],
                    ['type' => 'color', 'value' => 'Porcelain', 'stock' => 10],
                    ['type' => 'color', 'value' => 'Bay', 'stock' => 8],
                    ['type' => 'size', 'value' => '128GB', 'stock' => 15],
                    ['type' => 'size', 'value' => '256GB', 'stock' => 10],
                    ['type' => 'size', 'value' => '512GB', 'stock' => 5],
                ],
            ],
            [
                'name' => 'OnePlus 12',
                'category_slug' => 'handphone',
                'brand' => 'OnePlus',
                'price' => 11000000,
                'original_price' => 15000000,
                'stock' => 55,
                'sold' => 2345,
                'rating' => 4.6,
                'description' => 'OnePlus 12 dengan layar 2K 120Hz, Snapdragon 8 Gen 3, dan fast charging 100W. Kamera Hasselblad untuk hasil foto profesional.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1616348436168-de43ad0db179?w=600&h=600&fit=crop',
                    'https://images.unsplash.com/photo-1616348436168-de43ad0db179?w=600&h=600&fit=crop&sat=-20',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Silky Black', 'stock' => 20],
                    ['type' => 'color', 'value' => 'Flowy Emerald', 'stock' => 20],
                    ['type' => 'color', 'value' => 'Silver', 'stock' => 15],
                    ['type' => 'size', 'value' => '256GB', 'stock' => 35],
                    ['type' => 'size', 'value' => '512GB', 'stock' => 20],
                ],
            ],
            [
                'name' => 'iPhone 15 Pro',
                'category_slug' => 'handphone',
                'brand' => 'Apple',
                'price' => 15000000,
                'original_price' => 20000000,
                'stock' => 40,
                'sold' => 5678,
                'rating' => 4.7,
                'description' => 'iPhone 15 Pro dengan chip A17 Pro, titanium design ringan, dan USB-C. Action button untuk shortcut cepat.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&h=600&fit=crop',
                    'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&h=600&fit=crop&sat=-100',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Natural Titanium', 'stock' => 12],
                    ['type' => 'color', 'value' => 'Blue Titanium', 'stock' => 10],
                    ['type' => 'color', 'value' => 'White Titanium', 'stock' => 10],
                    ['type' => 'color', 'value' => 'Black Titanium', 'stock' => 8],
                    ['type' => 'size', 'value' => '128GB', 'stock' => 15],
                    ['type' => 'size', 'value' => '256GB', 'stock' => 15],
                    ['type' => 'size', 'value' => '512GB', 'stock' => 7],
                    ['type' => 'size', 'value' => '1TB', 'stock' => 3],
                ],
            ],
            [
                'name' => 'Samsung Galaxy Z Fold 5',
                'category_slug' => 'handphone',
                'brand' => 'Samsung',
                'price' => 25000000,
                'original_price' => 30000000,
                'stock' => 25,
                'sold' => 1234,
                'rating' => 4.8,
                'description' => 'Samsung Galaxy Z Fold 5 dengan layar lipat 7.6 inch Dynamic AMOLED 2X, multitasking terbaik, dan S-Pen support.',
                'is_flash_sale' => true,
                'discount' => 17,
                'flash_sale_end' => now()->addDays(2),
                'images' => [
                    'https://images.unsplash.com/photo-1610792516307-ea5acd5c3b3a?w=600&h=600&fit=crop',
                    'https://images.unsplash.com/photo-1610792516307-ea5acd5c3b3a?w=600&h=600&fit=crop&rot=90',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Icy Blue', 'stock' => 10],
                    ['type' => 'color', 'value' => 'Phantom Black', 'stock' => 8],
                    ['type' => 'color', 'value' => 'Cream', 'stock' => 7],
                    ['type' => 'size', 'value' => '256GB', 'stock' => 12],
                    ['type' => 'size', 'value' => '512GB', 'stock' => 8],
                    ['type' => 'size', 'value' => '1TB', 'stock' => 5],
                ],
            ],
            [
                'name' => 'Xiaomi 13T Pro',
                'category_slug' => 'handphone',
                'brand' => 'Xiaomi',
                'price' => 8000000,
                'original_price' => 11000000,
                'stock' => 80,
                'sold' => 7890,
                'rating' => 4.5,
                'description' => 'Xiaomi 13T Pro dengan kamera Leica, Dimensity 9200+, dan fast charging 120W. Layar AMOLED 6.67 inch 144Hz.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 35],
                    ['type' => 'color', 'value' => 'Blue', 'stock' => 25],
                    ['type' => 'color', 'value' => 'Silver', 'stock' => 20],
                    ['type' => 'size', 'value' => '256GB', 'stock' => 50],
                    ['type' => 'size', 'value' => '512GB', 'stock' => 30],
                ],
            ],
            [
                'name' => 'Vivo X100 Pro',
                'category_slug' => 'handphone',
                'brand' => 'Vivo',
                'price' => 14000000,
                'original_price' => 18000000,
                'stock' => 35,
                'sold' => 2345,
                'rating' => 4.6,
                'description' => 'Vivo X100 Pro dengan kamera Zeiss, Dimensity 9300, dan battery 5400mAh. Layar AMOLED 6.78 inch 120Hz.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1616348436168-de43ad0db179?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 15],
                    ['type' => 'color', 'value' => 'White', 'stock' => 10],
                    ['type' => 'color', 'value' => 'Red', 'stock' => 10],
                    ['type' => 'size', 'value' => '256GB', 'stock' => 20],
                    ['type' => 'size', 'value' => '512GB', 'stock' => 15],
                ],
            ],
            [
                'name' => 'Oppo Find X7 Ultra',
                'category_slug' => 'handphone',
                'brand' => 'Oppo',
                'price' => 17000000,
                'original_price' => 22000000,
                'stock' => 30,
                'sold' => 1234,
                'rating' => 4.6,
                'description' => 'Oppo Find X7 Ultra dengan kamera Hasselblad, Snapdragon 8 Gen 3, dan fast charging 100W.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 12],
                    ['type' => 'color', 'value' => 'Blue', 'stock' => 10],
                    ['type' => 'color', 'value' => 'Red', 'stock' => 8],
                    ['type' => 'size', 'value' => '256GB', 'stock' => 15],
                    ['type' => 'size', 'value' => '512GB', 'stock' => 10],
                    ['type' => 'size', 'value' => '1TB', 'stock' => 5],
                ],
            ],
            [
                'name' => 'Nothing Phone 2',
                'category_slug' => 'handphone',
                'brand' => 'Nothing',
                'price' => 9000000,
                'original_price' => 12000000,
                'stock' => 50,
                'sold' => 3456,
                'rating' => 4.5,
                'description' => 'Nothing Phone 2 dengan glyph interface, Snapdragon 8+ Gen 1, dan desain transparan ikonik.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1676494099158-6c1f6ef17d7c?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'White', 'stock' => 25],
                    ['type' => 'color', 'value' => 'Dark Grey', 'stock' => 25],
                    ['type' => 'size', 'value' => '128GB', 'stock' => 25],
                    ['type' => 'size', 'value' => '256GB', 'stock' => 15],
                    ['type' => 'size', 'value' => '512GB', 'stock' => 10],
                ],
            ],
            [
                'name' => 'Realme GT 5 Pro',
                'category_slug' => 'handphone',
                'brand' => 'Realme',
                'price' => 8000000,
                'original_price' => 11000000,
                'stock' => 70,
                'sold' => 5678,
                'rating' => 4.5,
                'description' => 'Realme GT 5 Pro dengan Snapdragon 8 Gen 3, fast charging 100W, dan layar 144Hz untuk gaming maksimal.',
                'is_flash_sale' => true,
                'discount' => 27,
                'flash_sale_end' => now()->addHours(6),
                'images' => [
                    'https://images.unsplash.com/photo-1616348436168-de43ad0db179?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 30],
                    ['type' => 'color', 'value' => 'White', 'stock' => 20],
                    ['type' => 'color', 'value' => 'Orange', 'stock' => 20],
                    ['type' => 'size', 'value' => '256GB', 'stock' => 40],
                    ['type' => 'size', 'value' => '512GB', 'stock' => 20],
                    ['type' => 'size', 'value' => '1TB', 'stock' => 10],
                ],
            ],
            [
                'name' => 'Asus ROG Phone 8',
                'category_slug' => 'handphone',
                'brand' => 'Asus',
                'price' => 13000000,
                'original_price' => 17000000,
                'stock' => 25,
                'sold' => 1234,
                'rating' => 4.7,
                'description' => 'Asus ROG Phone 8 untuk gaming dengan Snapdragon 8 Gen 3, baterai 6000mAh, dan AirTrigger 6.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 15],
                    ['type' => 'color', 'value' => 'White', 'stock' => 10],
                    ['type' => 'size', 'value' => '256GB', 'stock' => 15],
                    ['type' => 'size', 'value' => '512GB', 'stock' => 10],
                ],
            ],
            [
                'name' => 'Honor Magic 6 Pro',
                'category_slug' => 'handphone',
                'brand' => 'Honor',
                'price' => 16000000,
                'original_price' => 20000000,
                'stock' => 30,
                'sold' => 2345,
                'rating' => 4.6,
                'description' => 'Honor Magic 6 Pro dengan Snapdragon 8 Gen 3, kamera 180MP periscope, dan battery Silicon-Carbon 5600mAh.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 12],
                    ['type' => 'color', 'value' => 'Green', 'stock' => 10],
                    ['type' => 'color', 'value' => 'Purple', 'stock' => 8],
                    ['type' => 'size', 'value' => '256GB', 'stock' => 15],
                    ['type' => 'size', 'value' => '512GB', 'stock' => 10],
                    ['type' => 'size', 'value' => '1TB', 'stock' => 5],
                ],
            ],
            [
                'name' => 'iPhone SE 4',
                'category_slug' => 'handphone',
                'brand' => 'Apple',
                'price' => 8000000,
                'original_price' => 10000000,
                'stock' => 100,
                'sold' => 4567,
                'rating' => 4.4,
                'description' => 'iPhone SE 4 dengan chip A16 Bionic, desain modern tanpa home button, dan harga terjangkau.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Midnight', 'stock' => 40],
                    ['type' => 'color', 'value' => 'Starlight', 'stock' => 35],
                    ['type' => 'color', 'value' => 'Product Red', 'stock' => 25],
                    ['type' => 'size', 'value' => '64GB', 'stock' => 40],
                    ['type' => 'size', 'value' => '128GB', 'stock' => 35],
                    ['type' => 'size', 'value' => '256GB', 'stock' => 25],
                ],
            ],

            // ==================== LAPTOP (12 produk) ====================
            [
                'name' => 'Apple MacBook Air M3',
                'category_slug' => 'laptop',
                'brand' => 'Apple',
                'price' => 35000000,
                'original_price' => 42000000,
                'stock' => 30,
                'sold' => 567,
                'rating' => 4.9,
                'description' => 'MacBook Air dengan chip M3, layar Liquid Retina 13.6 inch, battery tahan seharian, dan desain super tipis.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&h=600&fit=crop',
                    'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&h=600&fit=crop&rot=90',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Silver', 'stock' => 10],
                    ['type' => 'color', 'value' => 'Space Gray', 'stock' => 8],
                    ['type' => 'color', 'value' => 'Midnight', 'stock' => 7],
                    ['type' => 'color', 'value' => 'Starlight', 'stock' => 5],
                    ['type' => 'size', 'value' => '8GB/256GB', 'stock' => 12],
                    ['type' => 'size', 'value' => '8GB/512GB', 'stock' => 10],
                    ['type' => 'size', 'value' => '16GB/512GB', 'stock' => 8],
                ],
            ],
            [
                'name' => 'Apple MacBook Pro M3',
                'category_slug' => 'laptop',
                'brand' => 'Apple',
                'price' => 45000000,
                'original_price' => 52000000,
                'stock' => 20,
                'sold' => 234,
                'rating' => 4.9,
                'description' => 'MacBook Pro dengan chip M3 Pro, layar Liquid Retina XDR 14.2 inch, untuk profesional kreatif.',
                'is_flash_sale' => true,
                'discount' => 15,
                'flash_sale_end' => now()->addDays(2),
                'images' => [
                    'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Silver', 'stock' => 10],
                    ['type' => 'color', 'value' => 'Space Black', 'stock' => 10],
                    ['type' => 'size', 'value' => '16GB/512GB', 'stock' => 8],
                    ['type' => 'size', 'value' => '16GB/1TB', 'stock' => 7],
                    ['type' => 'size', 'value' => '32GB/1TB', 'stock' => 5],
                ],
            ],
            [
                'name' => 'Dell XPS 15',
                'category_slug' => 'laptop',
                'brand' => 'Dell',
                'price' => 28000000,
                'original_price' => 35000000,
                'stock' => 15,
                'sold' => 456,
                'rating' => 4.8,
                'description' => 'Dell XPS 15 dengan layar OLED 3.5K, Intel Core i9 generasi 13, dan RTX 4070 untuk performa maksimal.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Platinum Silver', 'stock' => 15],
                    ['type' => 'size', 'value' => '16GB/512GB', 'stock' => 6],
                    ['type' => 'size', 'value' => '32GB/1TB', 'stock' => 5],
                    ['type' => 'size', 'value' => '64GB/2TB', 'stock' => 4],
                ],
            ],
            [
                'name' => 'ASUS ROG Zephyrus G14',
                'category_slug' => 'laptop',
                'brand' => 'Asus',
                'price' => 22000000,
                'original_price' => 28000000,
                'stock' => 25,
                'sold' => 789,
                'rating' => 4.7,
                'description' => 'Laptop gaming compact dengan AMD Ryzen 9, RTX 4060, dan layar 120Hz. Baterai tahan lama.',
                'is_flash_sale' => true,
                'discount' => 21,
                'flash_sale_end' => now()->addDays(1),
                'images' => [
                    'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'White', 'stock' => 13],
                    ['type' => 'color', 'value' => 'Gray', 'stock' => 12],
                    ['type' => 'size', 'value' => '16GB/512GB', 'stock' => 10],
                    ['type' => 'size', 'value' => '16GB/1TB', 'stock' => 8],
                    ['type' => 'size', 'value' => '32GB/1TB', 'stock' => 7],
                ],
            ],
            [
                'name' => 'Lenovo Legion 9i',
                'category_slug' => 'laptop',
                'brand' => 'Lenovo',
                'price' => 40000000,
                'original_price' => 48000000,
                'stock' => 10,
                'sold' => 123,
                'rating' => 4.8,
                'description' => 'Laptop gaming premium dengan water cooling, Intel Core i9, RTX 4090, dan AI chip.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Carbon Black', 'stock' => 10],
                    ['type' => 'size', 'value' => '32GB/1TB', 'stock' => 5],
                    ['type' => 'size', 'value' => '64GB/2TB', 'stock' => 5],
                ],
            ],
            [
                'name' => 'Microsoft Surface Laptop 5',
                'category_slug' => 'laptop',
                'brand' => 'Microsoft',
                'price' => 18000000,
                'original_price' => 23000000,
                'stock' => 30,
                'sold' => 567,
                'rating' => 4.6,
                'description' => 'Laptop premium dengan touchscreen 3:2, Intel Core i7, desain elegan dan tipis.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Platinum', 'stock' => 12],
                    ['type' => 'color', 'value' => 'Matte Black', 'stock' => 10],
                    ['type' => 'color', 'value' => 'Sandstone', 'stock' => 8],
                    ['type' => 'size', 'value' => '8GB/256GB', 'stock' => 15],
                    ['type' => 'size', 'value' => '16GB/512GB', 'stock' => 15],
                ],
            ],
            [
                'name' => 'HP Spectre x360',
                'category_slug' => 'laptop',
                'brand' => 'HP',
                'price' => 25000000,
                'original_price' => 31000000,
                'stock' => 20,
                'sold' => 345,
                'rating' => 4.7,
                'description' => 'Laptop 2-in-1 dengan layar OLED, Intel Evo, desain premium dengan gem-cut.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Nightfall Black', 'stock' => 10],
                    ['type' => 'color', 'value' => 'Nocturne Blue', 'stock' => 10],
                    ['type' => 'size', 'value' => '16GB/512GB', 'stock' => 8],
                    ['type' => 'size', 'value' => '16GB/1TB', 'stock' => 7],
                    ['type' => 'size', 'value' => '32GB/1TB', 'stock' => 5],
                ],
            ],
            [
                'name' => 'Acer Swift Edge 16',
                'category_slug' => 'laptop',
                'brand' => 'Acer',
                'price' => 15000000,
                'original_price' => 19000000,
                'stock' => 35,
                'sold' => 678,
                'rating' => 4.5,
                'description' => 'Laptop ultrabook super tipis dengan layar OLED 4K, AMD Ryzen 7, dan bobot hanya 1.17kg.',
                'is_flash_sale' => true,
                'discount' => 21,
                'flash_sale_end' => now()->addHours(36),
                'images' => [
                    'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Olivine Black', 'stock' => 35],
                    ['type' => 'size', 'value' => '16GB/512GB', 'stock' => 20],
                    ['type' => 'size', 'value' => '16GB/1TB', 'stock' => 15],
                ],
            ],
            [
                'name' => 'MSI Stealth 16 Studio',
                'category_slug' => 'laptop',
                'brand' => 'MSI',
                'price' => 32000000,
                'original_price' => 39000000,
                'stock' => 15,
                'sold' => 234,
                'rating' => 4.7,
                'description' => 'Laptop gaming tipis dengan Intel Core i9, RTX 4080, layar OLED 4K 120Hz.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 15],
                    ['type' => 'size', 'value' => '16GB/1TB', 'stock' => 8],
                    ['type' => 'size', 'value' => '32GB/2TB', 'stock' => 7],
                ],
            ],
            [
                'name' => 'Samsung Galaxy Book 3 Ultra',
                'category_slug' => 'laptop',
                'brand' => 'Samsung',
                'price' => 30000000,
                'original_price' => 36000000,
                'stock' => 20,
                'sold' => 345,
                'rating' => 4.7,
                'description' => 'Laptop premium dengan layar AMOLED 120Hz, Intel Core i9, RTX 4070, dan ecosystem Samsung.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Graphite', 'stock' => 10],
                    ['type' => 'color', 'value' => 'Beige', 'stock' => 10],
                    ['type' => 'size', 'value' => '16GB/512GB', 'stock' => 8],
                    ['type' => 'size', 'value' => '16GB/1TB', 'stock' => 7],
                    ['type' => 'size', 'value' => '32GB/1TB', 'stock' => 5],
                ],
            ],
            [
                'name' => 'Razer Blade 14',
                'category_slug' => 'laptop',
                'brand' => 'Razer',
                'price' => 35000000,
                'original_price' => 42000000,
                'stock' => 10,
                'sold' => 123,
                'rating' => 4.8,
                'description' => 'Laptop gaming kompak dengan build quality premium, AMD Ryzen 9, RTX 4070, layar 240Hz.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 5],
                    ['type' => 'color', 'value' => 'Mercury', 'stock' => 5],
                    ['type' => 'size', 'value' => '16GB/1TB', 'stock' => 6],
                    ['type' => 'size', 'value' => '32GB/2TB', 'stock' => 4],
                ],
            ],
            [
                'name' => 'Xiaomi Book Pro 16',
                'category_slug' => 'laptop',
                'brand' => 'Xiaomi',
                'price' => 16000000,
                'original_price' => 20000000,
                'stock' => 40,
                'sold' => 789,
                'rating' => 4.5,
                'description' => 'Laptop dengan layar 4K OLED, Intel Core i7, desain premium dengan harga terjangkau.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Gray', 'stock' => 20],
                    ['type' => 'color', 'value' => 'Silver', 'stock' => 20],
                    ['type' => 'size', 'value' => '16GB/512GB', 'stock' => 25],
                    ['type' => 'size', 'value' => '16GB/1TB', 'stock' => 15],
                ],
            ],

            // ==================== HEADSET (10 produk) ====================
            [
                'name' => 'Sony WH-1000XM5',
                'category_slug' => 'headset',
                'brand' => 'Sony',
                'price' => 7000000,
                'original_price' => 9500000,
                'stock' => 45,
                'sold' => 1234,
                'rating' => 4.9,
                'description' => 'Headphone noise cancelling terbaik dengan suara premium dan battery 30 jam, fast charging 3 menit untuk 3 jam pemakaian.',
                'is_flash_sale' => true,
                'discount' => 26,
                'flash_sale_end' => now()->addHours(36),
                'images' => [
                    'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 20],
                    ['type' => 'color', 'value' => 'Silver', 'stock' => 15],
                    ['type' => 'color', 'value' => 'Blue', 'stock' => 10],
                ],
            ],
            [
                'name' => 'AirPods Pro 2',
                'category_slug' => 'headset',
                'brand' => 'Apple',
                'price' => 3500000,
                'original_price' => 4500000,
                'stock' => 100,
                'sold' => 3456,
                'rating' => 4.8,
                'description' => 'Earbuds dengan noise cancellation terbaik untuk Apple ecosystem, chip H2, dan Adaptive Audio.',
                'is_flash_sale' => true,
                'discount' => 22,
                'flash_sale_end' => now()->addHours(6),
                'images' => [
                    'https://images.unsplash.com/photo-1600294037681-c80b4a3b4b19?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'White', 'stock' => 100],
                ],
            ],
            [
                'name' => 'JBL Flip 6',
                'category_slug' => 'headset',
                'brand' => 'JBL',
                'price' => 1800000,
                'original_price' => 2800000,
                'stock' => 150,
                'sold' => 4567,
                'rating' => 4.8,
                'description' => 'Speaker portable dengan suara stereo, waterproof IPX7, dan party boost untuk koneksi multiple speaker.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 40],
                    ['type' => 'color', 'value' => 'Red', 'stock' => 30],
                    ['type' => 'color', 'value' => 'Blue', 'stock' => 30],
                    ['type' => 'color', 'value' => 'Green', 'stock' => 30],
                    ['type' => 'color', 'value' => 'Squad', 'stock' => 20],
                ],
            ],
            [
                'name' => 'Bose QuietComfort Ultra',
                'category_slug' => 'headset',
                'brand' => 'Bose',
                'price' => 8000000,
                'original_price' => 10000000,
                'stock' => 30,
                'sold' => 567,
                'rating' => 4.9,
                'description' => 'Headphone dengan immersive audio dan noise cancellation terbaik di kelasnya, teknologi Bose Immersive Audio.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 15],
                    ['type' => 'color', 'value' => 'White', 'stock' => 8],
                    ['type' => 'color', 'value' => 'Sandstone', 'stock' => 7],
                ],
            ],
            [
                'name' => 'Samsung Galaxy Buds 2 Pro',
                'category_slug' => 'headset',
                'brand' => 'Samsung',
                'price' => 2500000,
                'original_price' => 3200000,
                'stock' => 80,
                'sold' => 2345,
                'rating' => 4.7,
                'description' => 'Earbuds dengan 24-bit Hi-Fi audio, ANC, dan seamless connectivity dengan Samsung devices.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 30],
                    ['type' => 'color', 'value' => 'White', 'stock' => 30],
                    ['type' => 'color', 'value' => 'Purple', 'stock' => 20],
                ],
            ],
            [
                'name' => 'Logitech G Pro X',
                'category_slug' => 'headset',
                'brand' => 'Logitech',
                'price' => 1800000,
                'original_price' => 2500000,
                'stock' => 60,
                'sold' => 1234,
                'rating' => 4.7,
                'description' => 'Headset gaming dengan Blue Voice technology, detachable mic, dan soundproofing untuk gaming kompetitif.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 35],
                    ['type' => 'color', 'value' => 'White', 'stock' => 25],
                ],
            ],
            [
                'name' => 'SteelSeries Arctis Nova Pro',
                'category_slug' => 'headset',
                'brand' => 'SteelSeries',
                'price' => 4000000,
                'original_price' => 5000000,
                'stock' => 40,
                'sold' => 567,
                'rating' => 4.8,
                'description' => 'Headset gaming premium dengan dual wireless, active noise cancellation, dan swappable battery system.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 40],
                ],
            ],
            [
                'name' => 'JBL Tune 770NC',
                'category_slug' => 'headset',
                'brand' => 'JBL',
                'price' => 1500000,
                'original_price' => 2200000,
                'stock' => 120,
                'sold' => 2345,
                'rating' => 4.6,
                'description' => 'Headphone ANC dengan battery 70 jam, fast charging, dan suara JBL Pure Bass.',
                'is_flash_sale' => true,
                'discount' => 32,
                'flash_sale_end' => now()->addHours(10),
                'images' => [
                    'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 50],
                    ['type' => 'color', 'value' => 'White', 'stock' => 40],
                    ['type' => 'color', 'value' => 'Blue', 'stock' => 30],
                ],
            ],
            [
                'name' => 'Anker Soundcore Space Q45',
                'category_slug' => 'headset',
                'brand' => 'Anker',
                'price' => 1800000,
                'original_price' => 2500000,
                'stock' => 90,
                'sold' => 1234,
                'rating' => 4.6,
                'description' => 'Headphone dengan noise cancellation terbaik di kelasnya, battery 50 jam, dan LDAC support.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 50],
                    ['type' => 'color', 'value' => 'White', 'stock' => 40],
                ],
            ],
            [
                'name' => 'Marshall Major IV',
                'category_slug' => 'headset',
                'brand' => 'Marshall',
                'price' => 2000000,
                'original_price' => 2700000,
                'stock' => 50,
                'sold' => 789,
                'rating' => 4.7,
                'description' => 'Headphone on-ear dengan desain klasik Marshall, battery 80 jam, dan fast charging 15 menit untuk 15 jam pemakaian.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 30],
                    ['type' => 'color', 'value' => 'Brown', 'stock' => 20],
                ],
            ],

            // ==================== SMARTWATCH (8 produk) ====================
            [
                'name' => 'Apple Watch Ultra 2',
                'category_slug' => 'smartwatch',
                'brand' => 'Apple',
                'price' => 12000000,
                'original_price' => 15000000,
                'stock' => 25,
                'sold' => 567,
                'rating' => 4.9,
                'description' => 'Smartwatch premium untuk outdoor dengan battery tahan lama, GPS dual-frequency, dan layar 3000 nits.',
                'is_flash_sale' => true,
                'discount' => 20,
                'flash_sale_end' => now()->addDays(3),
                'images' => [
                    'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Titanium', 'stock' => 25],
                    ['type' => 'size', 'value' => '49mm', 'stock' => 25],
                ],
            ],
            [
                'name' => 'Samsung Galaxy Watch 6 Classic',
                'category_slug' => 'smartwatch',
                'brand' => 'Samsung',
                'price' => 6000000,
                'original_price' => 8000000,
                'stock' => 50,
                'sold' => 1234,
                'rating' => 4.7,
                'description' => 'Smartwatch dengan rotating bezel klasik, sensor kesehatan lengkap, dan Wear OS.',
                'is_flash_sale' => true,
                'discount' => 25,
                'flash_sale_end' => now()->addHours(18),
                'images' => [
                    'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 25],
                    ['type' => 'color', 'value' => 'Silver', 'stock' => 25],
                    ['type' => 'size', 'value' => '40mm', 'stock' => 20],
                    ['type' => 'size', 'value' => '44mm', 'stock' => 20],
                    ['type' => 'size', 'value' => '47mm', 'stock' => 10],
                ],
            ],
            [
                'name' => 'Garmin Fenix 7X',
                'category_slug' => 'smartwatch',
                'brand' => 'Garmin',
                'price' => 15000000,
                'original_price' => 18000000,
                'stock' => 20,
                'sold' => 234,
                'rating' => 4.9,
                'description' => 'Smartwatch multisport dengan solar charging, mapping lengkap, dan battery tahan berbulan-bulan.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Carbon Gray', 'stock' => 12],
                    ['type' => 'color', 'value' => 'Titanium', 'stock' => 8],
                    ['type' => 'size', 'value' => '47mm', 'stock' => 12],
                    ['type' => 'size', 'value' => '51mm', 'stock' => 8],
                ],
            ],
            [
                'name' => 'Xiaomi Watch 2 Pro',
                'category_slug' => 'smartwatch',
                'brand' => 'Xiaomi',
                'price' => 2500000,
                'original_price' => 3500000,
                'stock' => 100,
                'sold' => 3456,
                'rating' => 4.6,
                'description' => 'Smartwatch Wear OS dengan harga terjangkau, layar AMOLED, dan GPS built-in.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 50],
                    ['type' => 'color', 'value' => 'Silver', 'stock' => 50],
                    ['type' => 'size', 'value' => '46mm', 'stock' => 100],
                ],
            ],
            [
                'name' => 'Google Pixel Watch 2',
                'category_slug' => 'smartwatch',
                'brand' => 'Google',
                'price' => 7000000,
                'original_price' => 9000000,
                'stock' => 30,
                'sold' => 567,
                'rating' => 4.7,
                'description' => 'Smartwatch dengan Fitbit integration, sensor kesehatan canggih, dan desain minimalis.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Matte Black', 'stock' => 12],
                    ['type' => 'color', 'value' => 'Polished Silver', 'stock' => 10],
                    ['type' => 'color', 'value' => 'Champagne Gold', 'stock' => 8],
                    ['type' => 'size', 'value' => '41mm', 'stock' => 30],
                ],
            ],
            [
                'name' => 'Huawei Watch GT 4',
                'category_slug' => 'smartwatch',
                'brand' => 'Huawei',
                'price' => 3500000,
                'original_price' => 4500000,
                'stock' => 60,
                'sold' => 1234,
                'rating' => 4.6,
                'description' => 'Smartwatch dengan battery tahan 14 hari, desain stylish, dan fitur kesehatan lengkap.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 20],
                    ['type' => 'color', 'value' => 'Silver', 'stock' => 15],
                    ['type' => 'color', 'value' => 'Green', 'stock' => 15],
                    ['type' => 'color', 'value' => 'Brown', 'stock' => 10],
                    ['type' => 'size', 'value' => '41mm', 'stock' => 30],
                    ['type' => 'size', 'value' => '46mm', 'stock' => 30],
                ],
            ],
            [
                'name' => 'Amazfit Balance',
                'category_slug' => 'smartwatch',
                'brand' => 'Amazfit',
                'price' => 2500000,
                'original_price' => 3200000,
                'stock' => 80,
                'sold' => 2345,
                'rating' => 4.5,
                'description' => 'Smartwatch dengan body composition analysis, battery tahan 14 hari, dan layar AMOLED.',
                'is_flash_sale' => true,
                'discount' => 22,
                'flash_sale_end' => now()->addHours(14),
                'images' => [
                    'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 35],
                    ['type' => 'color', 'value' => 'Silver', 'stock' => 25],
                    ['type' => 'color', 'value' => 'Gold', 'stock' => 20],
                    ['type' => 'size', 'value' => '46mm', 'stock' => 80],
                ],
            ],
            [
                'name' => 'Withings ScanWatch 2',
                'category_slug' => 'smartwatch',
                'brand' => 'Withings',
                'price' => 8000000,
                'original_price' => 10000000,
                'stock' => 15,
                'sold' => 123,
                'rating' => 4.7,
                'description' => 'Hybrid smartwatch dengan ECG dan SpO2, desain klasik seperti jam tangan analog.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'White', 'stock' => 5],
                    ['type' => 'color', 'value' => 'Black', 'stock' => 5],
                    ['type' => 'color', 'value' => 'Blue', 'stock' => 5],
                    ['type' => 'size', 'value' => '38mm', 'stock' => 8],
                    ['type' => 'size', 'value' => '42mm', 'stock' => 7],
                ],
            ],

            // ==================== ADAPTOR (10 produk) ====================
            [
                'name' => 'Adaptor iPhone 16 Pro',
                'category_slug' => 'adaptor',
                'brand' => 'Apple',
                'price' => 1000000,
                'original_price' => 1500000,
                'stock' => 200,
                'sold' => 763,
                'rating' => 4.7,
                'description' => 'Adaptor charger iPhone 16 Pro dengan fast charging 35W, kompatibel dengan USB-C.',
                'is_flash_sale' => true,
                'discount' => 33,
                'flash_sale_end' => now()->addHours(4),
                'images' => [
                    'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'White', 'stock' => 200],
                ],
            ],
            [
                'name' => 'Anker 737 Charger',
                'category_slug' => 'adaptor',
                'brand' => 'Anker',
                'price' => 1500000,
                'original_price' => 2000000,
                'stock' => 100,
                'sold' => 1234,
                'rating' => 4.8,
                'description' => 'Charger GaN 120W untuk 4 device sekaligus, dengan layar display real-time.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 100],
                ],
            ],
            [
                'name' => 'Anker Power Bank 26800',
                'category_slug' => 'adaptor',
                'brand' => 'Anker',
                'price' => 850000,
                'original_price' => 1200000,
                'stock' => 300,
                'sold' => 7890,
                'rating' => 4.7,
                'description' => 'Power bank 26800mAh dengan fast charging untuk 3 device sekaligus, kapasitas besar.',
                'is_flash_sale' => true,
                'discount' => 29,
                'flash_sale_end' => now()->addHours(30),
                'images' => [
                    'https://images.unsplash.com/photo-1609592423409-3b5c58570cac?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 300],
                ],
            ],
            [
                'name' => 'UGREEN Nexode 100W',
                'category_slug' => 'adaptor',
                'brand' => 'UGREEN',
                'price' => 800000,
                'original_price' => 1200000,
                'stock' => 150,
                'sold' => 2345,
                'rating' => 4.7,
                'description' => 'Charger GaN 100W dengan 4 port, kompak dan fast charging untuk laptop dan smartphone.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 80],
                    ['type' => 'color', 'value' => 'White', 'stock' => 70],
                ],
            ],
            [
                'name' => 'Belkin BoostCharge Pro',
                'category_slug' => 'adaptor',
                'brand' => 'Belkin',
                'price' => 1200000,
                'original_price' => 1600000,
                'stock' => 80,
                'sold' => 567,
                'rating' => 4.6,
                'description' => 'Charger 65W dengan MagSafe compatible, charging pad untuk Apple devices.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 40],
                    ['type' => 'color', 'value' => 'White', 'stock' => 40],
                ],
            ],
            [
                'name' => 'Baseus Blade 100W',
                'category_slug' => 'adaptor',
                'brand' => 'Baseus',
                'price' => 700000,
                'original_price' => 1000000,
                'stock' => 120,
                'sold' => 1234,
                'rating' => 4.6,
                'description' => 'Power bank tipis 100W dengan display digital, fast charging dan kompak.',
                'is_flash_sale' => true,
                'discount' => 30,
                'flash_sale_end' => now()->addHours(20),
                'images' => [
                    'https://images.unsplash.com/photo-1609592423409-3b5c58570cac?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 60],
                    ['type' => 'color', 'value' => 'White', 'stock' => 60],
                ],
            ],
            [
                'name' => 'Samsung 45W Charger',
                'category_slug' => 'adaptor',
                'brand' => 'Samsung',
                'price' => 500000,
                'original_price' => 700000,
                'stock' => 200,
                'sold' => 2345,
                'rating' => 4.6,
                'description' => 'Charger super fast charging 45W untuk Samsung devices, kompatibel dengan USB-C.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'White', 'stock' => 200],
                ],
            ],
            [
                'name' => 'Spigen GaN 65W',
                'category_slug' => 'adaptor',
                'brand' => 'Spigen',
                'price' => 600000,
                'original_price' => 900000,
                'stock' => 90,
                'sold' => 567,
                'rating' => 4.6,
                'description' => 'Charger GaN 65W compact untuk laptop dan phone, dengan 2 port USB-C.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 90],
                ],
            ],
            [
                'name' => 'Mophie Powerstation Plus',
                'category_slug' => 'adaptor',
                'brand' => 'Mophie',
                'price' => 1200000,
                'original_price' => 1600000,
                'stock' => 50,
                'sold' => 345,
                'rating' => 4.5,
                'description' => 'Power bank 10000mAh dengan built-in cable, kompak dan stylish.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1609592423409-3b5c58570cac?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 25],
                    ['type' => 'color', 'value' => 'Blue', 'stock' => 25],
                ],
            ],
            [
                'name' => 'Aukey Omnia 100W',
                'category_slug' => 'adaptor',
                'brand' => 'Aukey',
                'price' => 900000,
                'original_price' => 1300000,
                'stock' => 70,
                'sold' => 678,
                'rating' => 4.6,
                'description' => 'Charger GaN 100W dengan 4 port, kompak dan fast charging untuk semua perangkat.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 70],
                ],
            ],

            // ==================== CASE HP (15 produk) ====================
            [
                'name' => 'Case iPhone 15 Pro Max',
                'category_slug' => 'case',
                'brand' => 'Apple',
                'price' => 150000,
                'original_price' => 300000,
                'stock' => 500,
                'sold' => 3456,
                'rating' => 4.4,
                'description' => 'Case original iPhone 15 Pro Max dengan material silicone premium, anti slip dan nyaman di genggaman.',
                'is_flash_sale' => true,
                'discount' => 50,
                'flash_sale_end' => now()->addHours(2),
                'images' => [
                    'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 100],
                    ['type' => 'color', 'value' => 'Clear', 'stock' => 100],
                    ['type' => 'color', 'value' => 'Blue', 'stock' => 100],
                    ['type' => 'color', 'value' => 'Red', 'stock' => 100],
                    ['type' => 'color', 'value' => 'Green', 'stock' => 100],
                    ['type' => 'size', 'value' => 'iPhone 15', 'stock' => 120],
                    ['type' => 'size', 'value' => 'iPhone 15 Pro', 'stock' => 130],
                    ['type' => 'size', 'value' => 'iPhone 15 Pro Max', 'stock' => 150],
                    ['type' => 'size', 'value' => 'iPhone 14 Pro', 'stock' => 100],
                ],
            ],
            [
                'name' => 'Spigen Ultra Hybrid',
                'category_slug' => 'case',
                'brand' => 'Spigen',
                'price' => 200000,
                'original_price' => 350000,
                'stock' => 300,
                'sold' => 4567,
                'rating' => 4.7,
                'description' => 'Case transparant dengan anti-yellowing technology, military drop protection.',
                'is_flash_sale' => false,
                'discount' => 0,
                'images' => [
                    'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Clear', 'stock' => 200],
                    ['type' => 'color', 'value' => 'Matte Black', 'stock' => 100],
                    ['type' => 'size', 'value' => 'iPhone 15', 'stock' => 100],
                    ['type' => 'size', 'value' => 'iPhone 15 Pro', 'stock' => 100],
                    ['type' => 'size', 'value' => 'iPhone 15 Pro Max', 'stock' => 100],
                    ['type' => 'size', 'value' => 'Samsung S24', 'stock' => 100],
                ],
            ],
            [
                'name' => 'Case Samsung S24 Ultra',
                'category_slug' => 'case',
                'brand' => 'Samsung',
                'price' => 180000,
                'original_price' => 250000,
                'stock' => 200,
                'sold' => 2345,
                'rating' => 4.5,
                'description' => 'Case original Samsung S24 Ultra dengan grip nyaman, material premium.',
                'is_flash_sale' => true,
                'discount' => 28,
                'flash_sale_end' => now()->addHours(16),
                'images' => [
                    'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=600&h=600&fit=crop',
                ],
                'variants' => [
                    ['type' => 'color', 'value' => 'Black', 'stock' => 60],
                    ['type' => 'color', 'value' => 'Clear', 'stock' => 50],
                    ['type' => 'color', 'value' => 'Green', 'stock' => 50],
                    ['type' => 'color', 'value' => 'Purple', 'stock' => 40],
                    ['type' => 'size', 'value' => 'Samsung S24 Ultra', 'stock' => 80],
                    ['type' => 'size', 'value' => 'Samsung S24+', 'stock' => 60],
                    ['type' => 'size', 'value' => 'Samsung S24', 'stock' => 60],
                ],
            ],
        ];

        $this->insertProducts($products, $categories);
    }

    private function insertProducts(array $products, array $categories): void
    {
        foreach ($products as $productData) {
            $categoryId = $categories[$productData['category_slug']] ?? null;
            
            if (!$categoryId) {
                continue;
            }
            
            $slug = Str::slug($productData['name']);
            $originalSlug = $slug;
            $counter = 1;
            
            while (DB::table('products')->where('slug', $slug)->exists()) {
                $slug = $originalSlug . '-' . $counter;
                $counter++;
            }
            
            $productId = DB::table('products')->insertGetId([
                'name' => $productData['name'],
                'slug' => $slug,
                'category_id' => $categoryId,
                'brand' => $productData['brand'],
                'price' => $productData['price'],
                'original_price' => $productData['original_price'],
                'stock' => $productData['stock'],
                'sold' => $productData['sold'],
                'rating' => $productData['rating'],
                'description' => $productData['description'],
                'is_flash_sale' => $productData['is_flash_sale'],
                'discount' => $productData['discount'],
                'flash_sale_end' => $productData['flash_sale_end'] ?? null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
            
            // Insert images
            if (isset($productData['images']) && is_array($productData['images'])) {
                foreach ($productData['images'] as $index => $imageUrl) {
                    DB::table('product_images')->insert([
                        'product_id' => $productId,
                        'image_url' => $imageUrl,
                        'is_main' => $index === 0 ? 1 : 0,
                        'sort_order' => $index,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]);
                }
            }
            
            // Insert variants
            if (isset($productData['variants']) && is_array($productData['variants'])) {
                foreach ($productData['variants'] as $variant) {
                    DB::table('product_variants')->insert([
                        'product_id' => $productId,
                        'type' => $variant['type'],
                        'value' => $variant['value'],
                        'stock' => $variant['stock'] ?? null,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]);
                }
            }
        }
    }
}